### ISSUE TITLE
ask : initComponent();

### ISSUE THREAD

**Issue by amirisback** [MAqielHilmanM/DiaryApps#1]
Mau tau kenapa deklarasi variable viewnya menjadi global variable bukan di jadikan local variable saja?

**Comment by MAqielHilmanM** [comment]
kalau saya biasanya dibuat global agar dapat digunakan dimethod lain. 

Misalkan nanti terdapat method yang berfungsi untuk merubah view tersebut. Maka cukup dipanggil saja variablenya dan tidak perlu di inisialisasikan lg.
